version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./backend/mm-poker-tracker-0392299a602a.json:/app/mm-poker-tracker-0392299a602a.json
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/poker_analytics
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=poker_analytics

volumes:
  postgres_data:
