"""add_is_verified_column_to_players

Revision ID: 086a82aaceef
Revises: a7f9d2e8b1c4
Create Date: 2025-09-04 16:06:40.374505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086a82aaceef'
down_revision: Union[str, Sequence[str], None] = 'a7f9d2e8b1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_verified')
    # ### end Alembic commands ###
