"""add_game_number_to_sessions

Revision ID: 4a6d21595acf
Revises: f34e07806b85
Create Date: 2025-09-01 01:08:44.181038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6d21595acf'
down_revision: Union[str, Sequence[str], None] = 'f34e07806b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema and populate game_number values."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('game_number', sa.BigInteger(), nullable=True))
    
    # Data migration: populate game_number values for existing sessions
    connection = op.get_bind()
    
    # Get all games
    result = connection.execute(sa.text("SELECT id FROM games"))
    games = result.fetchall()
    
    for game in games:
        game_id = game.id
        
        # Get all sessions for this game, ordered chronologically
        sessions_result = connection.execute(sa.text("""
            SELECT id, started_at, created_at
            FROM sessions 
            WHERE game_id = :game_id
            ORDER BY 
                CASE 
                    WHEN started_at IS NOT NULL THEN 0 
                    ELSE 1 
                END,
                COALESCE(started_at, created_at),
                id
        """), {'game_id': str(game_id)})
        
        sessions = sessions_result.fetchall()
        
        # Assign game numbers sequentially
        for i, session in enumerate(sessions, 1):
            connection.execute(sa.text("""
                UPDATE sessions 
                SET game_number = :game_number 
                WHERE id = :session_id
            """), {
                'game_number': i,
                'session_id': str(session.id)
            })
    
    op.create_index('ix_sessions_game_number', 'sessions', ['game_id', 'game_number'], unique=False)
    op.create_unique_constraint('uq_sessions_game_number', 'sessions', ['game_id', 'game_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sessions_game_number', 'sessions', type_='unique')
    op.drop_index('ix_sessions_game_number', table_name='sessions')
    op.drop_column('sessions', 'game_number')
    # ### end Alembic commands ###
