"""add_game_statistics_config_table

Revision ID: b4bd1f7fa9f2
Revises: 5d994797a738
Create Date: 2025-09-24 17:13:00.911167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bd1f7fa9f2'
down_revision: Union[str, Sequence[str], None] = '5d994797a738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_statistics_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('config_name', sa.String(length=50), server_default='friendlyHighStack', nullable=False),
    sa.Column('vpip_tight_threshold', sa.BigInteger(), server_default='45', nullable=False),
    sa.Column('vpip_normal_threshold', sa.BigInteger(), server_default='55', nullable=False),
    sa.Column('vpip_loose_threshold', sa.BigInteger(), server_default='65', nullable=False),
    sa.Column('pfr_passive_threshold', sa.BigInteger(), server_default='10', nullable=False),
    sa.Column('pfr_normal_threshold', sa.BigInteger(), server_default='20', nullable=False),
    sa.Column('pfr_aggressive_threshold', sa.BigInteger(), server_default='30', nullable=False),
    sa.Column('af_passive_threshold', sa.BigInteger(), server_default='30', nullable=False),
    sa.Column('af_aggressive_threshold', sa.BigInteger(), server_default='45', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_statistics_config_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_statistics_config')),
    sa.UniqueConstraint('game_id', name=op.f('uq_game_statistics_config_game_id'))
    )
    op.create_index('ix_game_statistics_config_game_id', 'game_statistics_config', ['game_id'], unique=False)
    op.create_index('ix_game_statistics_config_type', 'game_statistics_config', ['config_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_statistics_config_type', table_name='game_statistics_config')
    op.drop_index('ix_game_statistics_config_game_id', table_name='game_statistics_config')
    op.drop_table('game_statistics_config')
    # ### end Alembic commands ###
